apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: app-name
  name: dc-name
  namespace: your-namespace
spec:
  replicas: 1 #initial replicas
  selector:
    deploymentconfig: dc-name
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: app-name
        deploymentconfig: dc-name
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: configmap-name
        image: pull-image.url/path/image-name:latest
        imagePullPolicy: Always
        name: container-name
        ports:
        - containerPort: 8080 # container exsposed port
          protocol: TCP
        resources:
          limits:
            memory: 1Gi # limits memory
          requests:
            cpu: 100m # initial cpu on start
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: image-pull-secret-name
      nodeSelector:
        node-role: worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: service-account-name
      serviceAccount: service-account-name
  test: false
  triggers:
  - type: ConfigChange

