kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-name
  namespace: your-namespace
spec:
  accessModes:  # array can more than one
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
