kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-rb-name
  namespace: namespace-name
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # default kube role
